engines/core/config/routes.rb
Samurai::Core::Engine.routes.draw do
  root to: "dashboard#index"

  devise_for :users, class_name: "Samurai::User", module: :devise

  namespace :admin do
    get '/' => 'admin#index'
    resources :users, only: :index
  end
end

engines/core/app/models/samurai/ability.rb
module Samurai
  class Ability
    include CanCan::Ability

    class_attribute :abilities
    self.abilities = Set.new

    def self.register_ability(ability)
        self.abilities.add(ability)
    end

    def self.remove_ability(ability)
        self.abilities.delete(ability)
    end

    def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
      if user.admin?
        can :manage, :all
      else
        can :read, :dashboard
      end

      self.abilities.each do |klass|
        ability = klass.new(user)
        @rules = rules + ability.send(:rules)
      end
    end
  end
end

engines/core/app/models/samurai/user.rb
module Samurai
  class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
    scope :ordered, -> { order('created_at desc') }
  end
end

engines/core/app/controllers/core/application_controller.rb
module Core
  class ApplicationController < ActionController::Base
  end
end

engines/core/app/controllers/samurai/admin/admin_controller.rb
module Samurai
  module Admin
    class AdminController < ApplicationController
      authorize_resource class: false

      def index
      end
    end
  end
end

engines/core/app/controllers/samurai/admin/users_controller.rb
module Samurai
  module Admin
    class UsersController < AdminController
      def index
        @users = Samurai::User.ordered
      end
    end
  end
end

engines/core/app/controllers/samurai/application_controller.rb
module Samurai
  class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    rescue_from CanCan::AccessDenied do |exception|
      render file: 'static/403.html', status: 403, layout: false
    end

    def current_ability
      @current_ability ||= Samurai::Ability.new(current_user)
    end
  end
end

engines/core/app/controllers/samurai/dashboard_controller.rb
module Samurai
  class DashboardController < ApplicationController
    authorize_resource class: false
    def index
    end
  end
end

engines/core/app/helpers/samurai/application_helper.rb
module Samurai
  module ApplicationHelper
    FLASH_CLASSES = {
      notice: 'alert alert-info',
      success: 'alert alert-success',
      alert: 'alert alert-danger',
      error: 'alert alert-danger'
    }

    def flash_class(level)
      FLASH_CLASSES[level]
    end

    def active(path)
      current_page?(path) ? 'active' : ''
    end
  end
end

engines/core/app/views/samurai/admin/admin/index.html.erb
<h2 class="pull-left">Admin</h2>
<%= render 'admin/shared/nav' %>
<hr>

<div class="row">
  <span data-samurai-hook='admin_dashboard_panel'></span>
  <div class="col-md-6">
    <!-- fill table content here -->
    <div class="panel panel-primary">
      <div class="panel-heading">
        Last 3 Users
      </div>
      <table class="table">
        <thead>
          <th>ID</th>
          <th>Email</th>
          <th>Singed Up</th>
        </thead>
        <tbody>
          <% Samurai::User.ordered.limit(3).each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.email %></td>
              <td><%= user.created_at.strftime("%d %b. %Y") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-body text-center">
        <%= link_to '...', samurai.admin_users_path %>
      </div>
    </div>
  </div>
</div>

engines/core/app/views/samurai/admin/shared/_nav.html.erb
<ul class="nav nav-pills navbar-right">
  <li data-samurai-hook='admin_dashboard' class="<%= active(admin_path) %>" role='presentation'>
    <%= link_to 'Dashboard', samurai.admin_path %>
  </li>

  <li class="<%= active(admin_users_path) %>">
    <%= link_to samurai.admin_users_path do %>
      Users
      <span class="badge"><%= Samurai::User.count %></span>
    <% end %>
  </li>
</ul>
<div class="clearfix"></div>

engines/core/app/views/samurai/admin/users/index.html.erb
<h2 class="pull-left">Users</h2>
<%= render 'admin/shared/nav' %>
<hr>
<div class="panel panel-primary">
  <div class="panel-heading">
    All Users
  </div>
  <table class="table">
    <thead>
      <th>ID</th>
      <th>Email</th>
      <th>Signed Up</th>
      <th>Admin?</th>
    </thead>
    <tbody>
    <%- @users.ordered.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime("%d %b. %Y") %></td>
        <td><%= user.admin? %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

engines/core/app/views/samurai/dashboard/index.html.erb
<h2>Dashboard</h2>
<hr>

<div class='row'>
  <span data-samurai-hook='dashboard'></span>
</div>