engines/tasks/config/routes.rb
Samurai::Core::Engine.routes.draw do
  scope module: 'tasks' do
    resources :tasks
  end

  namespace :admin do
    resources :tasks, only: :index
  end
end

engines/tasks/app/models/samurai/tasks/task.rb
module Samurai::Tasks
  class Task < ActiveRecord::Base
    belongs_to :user

    scope :ordered, -> { order('created_at desc') }

    if Samurai::Core.available?(:contacts)
      belongs_to :contact, class_name: 'Samurai::Contacts::Contact'
    end
  end
end

engines/tasks/app/controllers/samurai/admin/tasks_controller.rb
module Samurai
  module Admin
    class TasksController < Samurai::Admin::AdminController
      def index
        @tasks = Samurai::Tasks::Task.ordered
      end
    end
  end
end

engines/tasks/app/controllers/samurai/tasks/application_controller.rb
module Samurai
  module Tasks
    class ApplicationController < Samurai::ApplicationController
    end
  end
end

engines/tasks/app/controllers/samurai/tasks/tasks_controller.rb
require_dependency "samurai/application_controller"

module Samurai::Tasks
  class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    authorize_resource class: Samurai::Tasks::Task

    # GET /tasks
    def index
      @tasks = current_user.tasks
    end

    # GET /tasks/1
    def show
    end

    # GET /tasks/new
    def new
      @task = Task.new
    end

    # GET /tasks/1/edit
    def edit
    end

    # POST /tasks
    def create
      @task = Task.new(task_params)

      if @task.save
        redirect_to @task, notice: 'Task was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /tasks/1
    def update
      if @task.update(task_params)
        redirect_to @task, notice: 'Task was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /tasks/1
    def destroy
      @task.destroy
      redirect_to tasks_url, notice: 'Task was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_task
        @task = Task.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def task_params
        params.require(:task).permit(:title, :content, :user_id, :contact_id)
      end
  end
end

engines/tasks/app/helpers/samurai/tasks/application_helper.rb
module Samurai
  module Tasks
    module ApplicationHelper
    end
  end
end

engines/tasks/app/views/samurai/admin/tasks/index.html.erb
<h2 class="pull-left">Contacts</h2>
<%= render 'admin/shared/nav' %>
<hr>
<div class="panel panel-primary">
  <div class="panel-heading">
    All Tasks
  </div>
  <table class="table">
    <thead>
      <th>ID</th>
      <th>Title</th>
      <th>Content</th>
      <th>Created At</th>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.id %></td>
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= task.created_at.strftime("%d %b. %Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

engines/tasks/app/views/samurai/tasks/overrides/_admin_dashboard_tasks_list.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      Last 3 Tasks
    </div>
    <table class="table">
      <thead>
        <th>ID</th>
        <th>Title</th>
        <th>Content</th>
        <th>Created On</th>
      </thead>
      <tbody>
        <%- Samurai::Tasks::Task.all.each do |task| %>
          <tr>
            <td><%= task.id %></td>
            <td><%= task.title %></td>
            <td><%= task.content %></td>
            <td><%= task.created_at.strftime("%d %b. %Y") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="panel-body text-center">
      <%= link_to '...', tasks_path %>
    </div>
  </div>
</div>

engines/tasks/app/views/samurai/tasks/overrides/_admin_tasks_badges.html.erb
<li class="<%= active(samurai.admin_tasks_path) %>">
  <%= link_to samurai.admin_tasks_path do %>
    Tasks
    <span class="badge"><%= Samurai::Tasks::Task.count %></span>
  <% end %>
</li>

engines/tasks/app/views/samurai/tasks/overrides/_contact_tasks_list.html.erb
<hr>
<div class="panel panel-primary">
  <div class="panel-heading">
    Tasks for this contact
  </div>
  <table class="table">
    <thead>
      <th>ID</th>
      <th>Title</th>
      <th>Content</th>
      <th>Created On</th>
      <th></th>
    </thead>
    <tbody>
      <% @contact.tasks.each do |task| %>
        <tr>
          <td><%= task.id %></td>
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= task.created_at.strftime("%d %b. %Y") %></td>
          <td>
            <%= link_to 'Show', [samurai, task], class: 'btn btn-primary' %>
            <%= link_to 'Edit', samurai.edit_task_path(task), class: 'btn btn-primary' %>
            <%= link_to 'Destroy', [samurai, task], class: 'btn btn-primary' , method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

engines/tasks/app/views/samurai/tasks/overrides/_dashboard_tasks_list.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      Last 3 Tasks
    </div>
    <table class="table">
      <thead>
        <th>ID</th>
        <th>Title</th>
        <th>Content</th>
        <th>Created On</th>
      </thead>
      <tbody>
        <%- @tasks.limit(3).each do |task| %>
          <tr>
          <td><%= task.id %></td>
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= task.created_at.strftime("%d %b. %Y") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="panel-body text-center">
      <%= link_to '...', tasks_path %>
    </div>
  </div>
</div>

engines/tasks/app/views/samurai/tasks/overrides/_tasks_link.html.erb
<li class="<%= active(samurai.tasks_path) %>">
  <%= link_to 'Tasks', samurai.tasks_path %>
</li>

engines/tasks/app/views/samurai/tasks/tasks/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2>
        <%= pluralize(@task.errors.count, "error") %>
        prohibited this task from being saved:</h2>
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :title, class: "control-label" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :content, class: "control-label" %>
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :user_id, class: "control-label" %>
      <%= f.select :user_id, Samurai::User.all.collect { |p| [ p.email, p.id ] }, { selected: current_user.id }, class: "form-control" %>
    </div>

    <%- if Samurai::Core.available?(:contacts) %>
      <div class="form-group">
        <%= f.label :contact_id, class: "control-label" %>
        <%= f.select :contact_id, current_user.contacts.collect { |p| [ p.email, p.id ] }, { allow_blank: true }, class: "form-control" %>
      </div>
    <% end %>
  </div>
</div>

engines/tasks/app/views/samurai/tasks/tasks/edit.html.erb
<h2>Editing Task</h2>
<hr>
<%= form_for([samurai, @task]) do |f| %>
  <%= render 'form', f: f %>
  <div class="form-group">
    <div>
      <%= f.submit "Update Task", class: "btn btn-primary" %>
      <%= link_to 'Back', samurai.tasks_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

engines/tasks/app/views/samurai/tasks/tasks/index.html.erb
<%= link_to 'New Task', samurai.new_task_path, class: 'pull-right btn btn-primary' %>
<h2>Listing Task</h2>
<hr>
<div class="panel panel-primary">
  <div class="panel-heading">
    My Tasks
  </div>
  <table class="table">
    <thead>
      <th>ID</th>
      <th>Title</th>
      <th>Content</th>
      <th>Created At</th>
      <th></th>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.id %></td>
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= task.created_at.strftime("%d %b. %Y") %></td>
          <td>
            <%= link_to 'Show', [samurai, task], class: 'btn btn-primary' %>
            <%= link_to 'Edit', samurai.edit_task_path(task), class: 'btn btn-primary' %>
            <%= link_to 'Destroy', [samurai, task], class: 'btn btn-primary' , method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

engines/tasks/app/views/samurai/tasks/tasks/new.html.erb
<h2>New Task</h2>
<hr>
<%= form_for([samurai, @task]) do |f| %>
  <%= render 'form', f: f %>
  <div class="form-group">
    <div>
      <%= f.submit "Create Task", class: "btn btn-primary" %>
      <%= link_to 'Back', samurai.tasks_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

engines/tasks/app/views/samurai/tasks/tasks/show.html.erb
<h2><%= @task.title %></h2>
<hr>
<div class="row">
  <div class="col-md-8">
    <strong>Title:</strong>
    <%= @task.title %>
    <br/>
    <strong>Content:</strong>
    <%= @task.content %>
    <br/>
    <strong>User:</strong>
    <%= @task.user.email %>
    <br/>
    <strong>Contact:</strong>
    <%= @task.try(:contact) ? @task.contact.email : '' %>
    <br/>
  </div>
</div>
<hr>
<%= link_to 'Edit', samurai.edit_task_path(@task), class: "btn btn-primary" %> <%= link_to 'Back', samurai.tasks_path, class: 'btn btn-default' %>